version: 3

tasks:
  rust-fmt-and-lint:
    desc: Format and lint the Rust code
    internal: true
    
    method: checksum
    sources:
      - language-server/src/**/*.rs
    
    cmds:
      - cargo fmt --check --toolchain nightly
      - cargo clippy

  vscode-fmt-and-lint:
    desc: Format and lint the VSCode package
    dir: vscode
    internal: true

    method: checksum
    sources:
      - client/**/*
      - server/**/*
      - syntaxes/*
      - package.json
    
    cmds:
      - npm run fmt-check
      - npm run lint

  fmt-and-lint:
    desc: Format and lint all code.

    deps:
      - rust-fmt-and-lint
      - vscode-fmt-and-lint
    
