version: 3

tasks:
  rust-build:
    desc: Compile the language server binary.
    dir: language-server
    
    method: checksum
    sources:
      - src/**/*.rs
      - '*.toml'
    
    cmds:
      - cargo build

  package-vscode:
    desc: Package the VSCode extension into a VSIX file.
    dir: vscode

    method: checksum
    sources:
      - client/**/*
      - server/**/*
      - build/*
      - syntaxes/*
      - package.json
      - package-lock.json
    
    cmds:
      - npm run package

  build:
    desc: Build the language server and package the VSCode extension.
    
    deps:
      - package-vscode

  install:
    desc: Build the language server, package the extension, then install it.
    
    method: checksum
    sources:
      - vscode/pest.vsix

    deps:
      - build
    cmds:
      - code --install-extension ./vscode/pest.vsix
  
  rust-fmt-and-lint:
    desc: Format and lint the Rust code
    internal: true
    
    method: checksum
    sources:
      - language-server/src/**/*.rs
    
    cmds:
      - cargo fmt --check
      - cargo clippy

  vscode-fmt-and-lint:
    desc: Format and lint the VSCode package
    dir: vscode
    internal: true

    method: checksum
    sources:
      - client/**/*
      - server/**/*
      - syntaxes/*
      - package.json
    
    cmds:
      - npm run fmt-check
      - npm run lint

  fmt-and-lint:
    desc: Format and lint all code.

    deps:
      - rust-fmt-and-lint
      - vscode-fmt-and-lint
    
