<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>name</key>
        <string>Pest</string>
        <key>scopeName</key>
        <string>source.pest</string>
        <key>fileTypes</key>
        <array>
        	<string>pest</string>
        </array>
        <key>patterns</key>
        <array>
            <dict>
                <key>include</key>
                <string>#keywords</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#strings</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#comments</string>
            </dict>
            <dict>
                <key>include</key>
                <string>#multilinecomments</string>
            </dict>
        </array>
        <key>repository</key>
        <dict>
            <key>keywords</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>keyword.control.pest</string>
                        <key>match</key>
                        <string>PUSH|(POP|PEEK)(_ALL)?</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>variable.language.implicit.pest</string>
                        <key>match</key>
                        <string>WHITESPACE|COMMENT</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.borders.pest</string>
                        <key>match</key>
                        <string>[SE]OI</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.ascii.pest</string>
                        <key>match</key>
                        <string>NEWLINE|ASCII_(ALPHA(_UPPER|_LOWER|NUMERIC)?|(NONZERO_|BIN_|OCT_|HEX_)?DIGIT)</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.unicode.letter.pest</string>
                        <key>match</key>
                        <string>ANY|((UPPER|LOWER|TITLE)CASE_|CASED_|MODIFIER_|OTHER_)?LETTER</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.unicode.mark.pest</string>
                        <key>match</key>
                        <string>(NONSPACING_|SPACING_|ENCLOSING_)?MARK</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.unicode.number.pest</string>
                        <key>match</key>
                        <string>(DECIMAL_|LETTER_|OTHER_)?NUMBER</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.unicode.punctuation.pest</string>
                        <key>match</key>
                        <string>(CONNECTOR_|DASH_|OPEN_|CLOSE_|INITIAL_|FINAL_|OTHER_)?PUNCTUATION</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.unicode.symbol.pest</string>
                        <key>match</key>
                        <string>(MATH_|CURRENCY_|MODIFIER_|OTHER_)?SYMBOL</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.unicode.separator.pest</string>
                        <key>match</key>
                        <string>(SPACE_|LINE_|PARAGRAPH_)?SEPARATOR</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.unicode.other.pest</string>
                        <key>match</key>
                        <string>CONTROL|FORMAT|SURROGATE|PRIVATE_USE|UNASSIGNED</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>constant.language.character.unicode.binary.pest</string>
                        <key>match</key>
                        <string>
                            ALPHABETIC|BIDI_CONTROL|CASE_IGNORABLE|CASED|CHANGES_WHEN_CASEFOLDED|CHANGES_WHEN_CASEMAPPED|CHANGES_WHEN_LOWERCASED|CHANGES_WHEN_TITLECASED|CHANGES_WHEN_UPPERCASED|DASH|DEFAULT_IGNORABLE_CODE_POINT|DEPRECATED|DIACRITIC|EXTENDER|GRAPHEME_BASE|GRAPHEME_EXTEND|GRAPHEME_LINK|HEX_DIGIT|HYPHEN|IDS_BINARY_OPERATOR|IDS_TRINARY_OPERATOR|ID_CONTINUE|ID_START|IDEOGRAPHIC|JOIN_CONTROL|LOGICAL_ORDER_EXCEPTION|LOWERCASE|MATH|NONCHARACTER_CODE_POINT|OTHER_ALPHABETIC|OTHER_DEFAULT_IGNORABLE_CODE_POINT|OTHER_GRAPHEME_EXTEND|OTHER_ID_CONTINUE|OTHER_ID_START|OTHER_LOWERCASE|OTHER_MATH|OTHER_UPPERCASE|PATTERN_SYNTAX|PATTERN_WHITE_SPACE|PREPENDED_CONCATENATION_MARK|QUOTATION_MARK|RADICAL|REGIONAL_INDICATOR|SENTENCE_TERMINAL|SOFT_DOTTED|TERMINAL_PUNCTUATION|UNIFIED_IDEOGRAPH|UPPERCASE|VARIATION_SELECTOR|WHITE_SPACE|XID_CONTINUE|XID_START
                        </string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>keyword.operator.pest</string>
                        <key>match</key>
                        <string>-|\.\.|!|~|_|@|\$</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>keyword.operator.repetition.pest</string>
                        <key>match</key>
                        <string>\+|\*|\?|{\s*[0-9]+\s*,\s*}|{\s*,\s*[0-9]+\s*}|{\s*[0-9]+\s*,\s*[0-9]+\s*}</string>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>variable.name.pest</string>
                        <key>match</key>
                        <string>[A-Za-z_][A-Za-z0-9_]*</string>
                    </dict>
                </array>
            </dict>
            <key>strings</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.double.pest</string>
                        <key>begin</key>
                        <string>"</string>
                        <key>end</key>
                        <string>"</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#characterescape</string>
                            </dict>
                        </array>
                    </dict>
                    <dict>
                        <key>name</key>
                        <string>string.quoted.single.pest</string>
                        <key>begin</key>
                        <string>'</string>
                        <key>end</key>
                        <string>'</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#characterescape</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>comments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>comment.line.pest</string>
                        <key>match</key>
                        <string>//.*</string>
                    </dict>
                </array>
            </dict>
            <key>multilinecomments</key>
            <dict>
                <key>patterns</key>
                <array>
                    <dict>
                        <key>name</key>
                        <string>comment.block.pest</string>
                        <key>begin</key>
                        <string>/\*</string>
                        <key>end</key>
                        <string>\*/</string>
                        <key>patterns</key>
                        <array>
                            <dict>
                                <key>include</key>
                                <string>#multilinecomments</string>
                            </dict>
                        </array>
                    </dict>
                </array>
            </dict>
            <key>characterescape</key>
            <dict>
                <key>name</key>
                <string>constant.character.escape.pest</string>
                <key>match</key>
                <string>((\\u\{[a-fA-F0-9]{4}\})|(\\.))</string>
            </dict>
        </dict>
    </dict>
</plist>