name: Package VSCode Extension

on:
  push:
  pull_request:

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          kind: package-vscode
          toolchain: 1.62.0
      - name: Package Extension
        run: task package-vscode
      - uses: actions/upload-artifact@v3
        with:
          name: pest-vscode
          path: vscode/pest.vsix
